---
# yaml-language-server: $schema=./../../../schemas/main-schema.json

parameters:
  - &lidoLocator "0xC1d0b3DE6792Bf6b4b37EccdcC24e45978Cfd2Eb"
  - &lido "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
  - &stakingRouter "0xFdDf38947aFB03C621C71b06C9C70bce73f12999"
  - &accountingOracle "0x852deD011285fe67063a08005c71a85690503Cee"
  - &agent "0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c"
  - &elRewardsVault "0x388C818CA8B9251b393131C08a736A67ccB19297"
  - &legacyOracle "0x442af784A788A5bd6F42A01Ebe9F287a871243fb"
  - &burner "0xD15a672319Cf0352560eE76d9e89eAB0889046D3"
  - &treasury "0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c"
  - &withdrawalQueue "0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1"
  - &withdrawalVault "0xB9D7934878B5FB9610B3fE8A5e441e8fad7E293f"
  - &oracleDaemonConfig "0xbf05A929c3D7885a6aeAd833a992dA6E5ac23b09"
  - &postTokenRebaseReceiver "0xe6793B9e4FbA7DE0ee833F9D02bba7DB5EB27823"
  - &DEPOSIT_CONTRACT "0x00000000219ab540356cBB839Cbe05303d7705Fa"
  - &validatorsExitBusOracle "0x0De4Ea0184c2ad0BacA7183356Aea5B8d5Bf5c6e"
  - &updateTargetValidatorLimits "0x161a4552A625844c822954C5AcBac928ee0f399B"
  - &sdvtModule "0xaE7B191A31f627b4eB1d4DaC64eaB9976995b433"
  - &sdvtCommittee "0x08637515E85A4633E23dfc7861e2A9f53af640f7"

misc:
  - &depositSecurityModuleMaxOperatorPerUnvetting 200
  - &oracleReportSanityCheckerMaxValidatorsExits 600
  - &oracleReportSanityCheckerMaxValidatorsExitsRevert 601
  - &oracleReportSanityCheckerMaxValidatorsExitsPerDay 9000
  - &oracleReportSanityCheckerMaxValidatorsExitsPerDayRevert 9001
  - &oracleReportSanityCheckerExtraDataItemPerTransaction 8
  - &oracleReportSanityCheckerExtraDataItemPerTransactionRevert 9
  - &oracleReportSanityCheckerNOPerExtraDataItem 24
  - &oracleReportSanityCheckerNOPerExtraDataItemRevert 25
  - &oracleReportSanityCheckerSecondOpinionOracle "0x0000000000000000000000000000000000000000"
  - &oracleReportSanityCheckerReportLimits [9000, 43200, 1000, 50, 600, 8, 24, 7680, 750000, 1000, 101, 50]
  - &dsmGuardians [
      "0x5fd0dDbC3351d009eb3f88DE7Cd081a614C519F1",
      "0x7912Fa976BcDe9c2cf728e213e892AD7588E6AaF",
      "0x14D5d5B71E048d2D75a39FfC5B407e3a3AB6F314",
      "0xf82D88217C249297C6037BA77CE34b3d8a90ab43",
      "0xa56b128Ea2Ea237052b0fA2a96a387C0E43157d8",
      "0xd4EF84b638B334699bcf5AF4B0410B8CCD71943f",
    ]
  - &stakingModuleCuratedType "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &maxUint256 115792089237316195423570985008687907853269984665640564039457584007913129639935

deployed:
  l1:
    - &lidoLocatorImpl "0x3abc4764f0237923d52056cfba7e9aebf87113d3"
    - &stakingRouterImpl "0x89eda99c0551d4320b56f82dde8df2f8d2ef81aa"
    - &nodeOperatorRegistryImpl "0x1770044a38402e3cfca2fcfa0c84a093c9b42135"
    - &depositSecurityModule "0xfFA96D84dEF2EA035c7AB153D8B991128e3d72fD"
    - &accountingOracleImpl "0x0e65898527e77210fb0133d00dd4c0e86dc29bc7"
    - &oracleReportSanityChecker "0x6232397ebac4f5772e53285B26c47914E9461E75"

roles:
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &STAKING_MODULE_UNVETTING_ROLE "0x240525496a9dc32284b17ce03b43e539e4bd81414634ee54395030d793463b57"
  - &STAKING_ROUTER_ROLE "0xbb75b874360e0bfd87f964eadd8276d8efb7c942134fc329b513032d0803e0c6"
  - &ALL_LIMITS_MANAGER_ROLE "0x5bf88568a012dfc9fe67407ad6775052bddc4ac89902dea1f4373ef5d9f1e35b"
  - &ANNUAL_BALANCE_INCREASE_LIMIT_MANAGER_ROLE "0x12c02753cd3d584dc4bb965eb0c88392c4c4d7c00433fdb7490d33c61ea57622"
  - &APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE "0x14ca7b84baa11a976283347b0159b8ddf2dcf5fd5cf613cc567a3423cf510119"
  - &EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE "0x60b9982471bc0620c7b74959f48a86c55c92c11876fddc5b0b54d1ec47153e5d"
  - &INITIAL_SLASHING_AND_PENALTIES_MANAGER_ROLE "0xebfa317a5d279811b024586b17a50f48924bce86f6293b233927322d7209b507"
  - &MAX_ITEMS_PER_EXTRA_DATA_TRANSACTION_ROLE "0x13445b811594f3a8800b82296d63f371c695d2f86c1069c899ded3d73f523d2e"
  - &MAX_NODE_OPERATORS_PER_EXTRA_DATA_ITEM_ROLE "0xb3f2d16385bde8a7121e101a021aff43bbe4d4137a587832caf1f583b9d34395"
  - &MAX_POSITIVE_TOKEN_REBASE_MANAGER_ROLE "0x78de2bab4a3a0c88f50b6bb7c2290e0eb46bc61d575eae694d8bffbc2ca98c92"
  - &MAX_VALIDATOR_EXIT_REQUESTS_PER_REPORT_ROLE "0x9925400e72399e0a89e9b346878fc47ac0031526d0e060e33ff372d7a5d11ba8"
  - &REQUEST_TIMESTAMP_MARGIN_MANAGER_ROLE "0x2f8719116fbba3aba2a39759e34dcd29ea3516f7568c8321695aaea208280cd3"
  - &SECOND_OPINION_MANAGER_ROLE "0xaa0e0f619f5a9368ee035bae759cfe7da8958f44bd71456a05198effc68ea647"
  - &SHARE_RATE_DEVIATION_LIMIT_MANAGER_ROLE "0x7b21c0949109e9e143f66d6aa1f8a065b3f4ab47ee9f84f6837fd0490eace4d5"

l1:
  rpcUrl: L1_MAINNET_RPC_URL
  explorerHostname: api.etherscan.io
  explorerTokenEnv: ETHERSCAN_TOKEN
  contracts:
    lidoLocator:
      name: LidoLocator
      address: *lidoLocatorImpl
      checks:
        accountingOracle: *accountingOracle
        burner: *burner
        coreComponents:
          [*elRewardsVault, *oracleReportSanityChecker, *stakingRouter, *treasury, *withdrawalQueue, *withdrawalVault]
        depositSecurityModule: *depositSecurityModule
        elRewardsVault: *elRewardsVault
        legacyOracle: *legacyOracle
        lido: *lido
        oracleDaemonConfig: *oracleDaemonConfig
        oracleReportComponentsForLido: null
        oracleReportSanityChecker: *oracleReportSanityChecker
        postTokenRebaseReceiver: *postTokenRebaseReceiver
        stakingRouter: *stakingRouter
        treasury: *treasury
        validatorsExitBusOracle: *validatorsExitBusOracle
        withdrawalQueue: *withdrawalQueue
        withdrawalVault: *withdrawalVault
    stakingRouterImpl:
      name: StakingRouterImpl
      address: *stakingRouterImpl
      checks:
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        DEPOSIT_CONTRACT: *DEPOSIT_CONTRACT
        FEE_PRECISION_POINTS: 100000000000000000000
        MANAGE_WITHDRAWAL_CREDENTIALS_ROLE: "0xe7c742a54cd11fc9749a47ab34bdcd7327820908e8d0d48b4a5c7f17b0294098"
        MAX_STAKING_MODULES_COUNT: 32
        MAX_STAKING_MODULE_NAME_LENGTH: 31
        REPORT_EXITED_VALIDATORS_ROLE: "0xc23292b191d95d2a7dd94fc6436eb44338fda9e1307d9394fd27c28157c1b33c"
        REPORT_REWARDS_MINTED_ROLE: "0x779e5c23cb7a5bcb9bfe1e9a5165a00057f12bcdfd13e374540fdf1a1cd91137"
        STAKING_MODULE_MANAGE_ROLE: "0x3105bcbf19d4417b73ae0e58d508a65ecf75665e46c2622d8521732de6080c48"
        STAKING_MODULE_UNVETTING_ROLE: "0x240525496a9dc32284b17ce03b43e539e4bd81414634ee54395030d793463b57"
        TOTAL_BASIS_POINTS: 10000
        UNSAFE_SET_EXITED_VALIDATORS_ROLE: "0x55180e25fcacf9af017d35d497765476319b23896daa1f9bc2b38fa80b36a163"
        getAllNodeOperatorDigests: null
        getAllStakingModuleDigests: null
        getContractVersion: *maxUint256
        getDepositsAllocation: null
        getLido: "0x0000000000000000000000000000000000000000"
        getNodeOperatorDigests: null
        getNodeOperatorSummary: null
        getRoleAdmin: null
        getRoleMember: null
        getRoleMemberCount:
          - args: [*STAKING_MODULE_UNVETTING_ROLE]
            result: 0
          - args: [*DEFAULT_ADMIN_ROLE]
            result: 0
        getStakingFeeAggregateDistribution: null
        getStakingFeeAggregateDistributionE4Precision: null
        getStakingModule: null
        getStakingModuleActiveValidatorsCount: null
        getStakingModuleDigests: null
        getStakingModuleIds: null
        getStakingModuleIsActive: null
        getStakingModuleIsDepositsPaused: null
        getStakingModuleIsStopped: null
        getStakingModuleLastDepositBlock: null
        getStakingModuleMaxDepositsCount: null
        getStakingModuleMaxDepositsPerBlock: null
        getStakingModuleMinDepositBlockDistance: null
        getStakingModuleNonce: null
        getStakingModuleStatus: null
        getStakingModuleSummary: null
        getStakingModules: null
        getStakingModulesCount: null
        getStakingRewardsDistribution: null
        getTotalFeeE4Precision: null
        getWithdrawalCredentials: "0x0000000000000000000000000000000000000000000000000000000000000000"
        hasRole: null
        hasStakingModule: null
        supportsInterface: null
    nodeOperatorRegistryImpl:
      name: NodeOperatorRegistryImpl
      address: *nodeOperatorRegistryImpl
      checks:
        MANAGE_NODE_OPERATOR_ROLE: "0x78523850fdd761612f46e844cf5a16bda6b3151d6ae961fd7e8e7b92bfbca7f8"
        MANAGE_SIGNING_KEYS: "0x75abc64490e17b40ea1e66691c3eb493647b24430b358bd87ec3e5127f1621ee"
        MAX_NODE_OPERATORS_COUNT: 200
        MAX_NODE_OPERATOR_NAME_LENGTH: 255
        MAX_STUCK_PENALTY_DELAY: 31536000
        SET_NODE_OPERATOR_LIMIT_ROLE: "0x07b39e0faf2521001ae4e58cb9ffd3840a63e205d288dc9c93c3774f0d794754"
        STAKING_ROUTER_ROLE: *STAKING_ROUTER_ROLE
        appId: null
        allowRecoverability: null
        canPerform: null
        getActiveNodeOperatorsCount: null
        getContractVersion: *maxUint256
        getEVMScriptExecutor: null
        getEVMScriptRegistry: null
        getInitializationBlock: *maxUint256
        getKeysOpIndex: null
        getLocator: null
        getNodeOperator: null
        getNodeOperatorIds: null
        getNodeOperatorIsActive: null
        getNodeOperatorSummary: null
        getNodeOperatorsCount: null
        getNonce: null
        getRecoveryVault: null
        getRewardDistributionState: null
        getRewardsDistribution: null
        getSigningKey: null
        getSigningKeys: null
        getStakingModuleSummary: null
        getStuckPenaltyDelay: null
        getTotalSigningKeyCount: null
        getType: *stakingModuleCuratedType
        getUnusedSigningKeyCount: null
        hasInitialized: false
        isOperatorPenalized: null
        isOperatorPenaltyCleared: null
        isPetrified: true
        kernel: null
    depositSecurityModule:
      name: DepositSecurityModule
      address: *depositSecurityModule
      checks:
        ATTEST_MESSAGE_PREFIX: null
        DEPOSIT_CONTRACT: *DEPOSIT_CONTRACT
        LIDO: *lido
        PAUSE_MESSAGE_PREFIX: null
        STAKING_ROUTER: *stakingRouter
        UNVET_MESSAGE_PREFIX: null
        VERSION: 3
        canDeposit: null
        getGuardianIndex: null
        getGuardianQuorum: 4
        getGuardians: *dsmGuardians
        getLastDepositBlock: null
        getMaxOperatorsPerUnvetting: *depositSecurityModuleMaxOperatorPerUnvetting
        getOwner: *agent
        getPauseIntentValidityPeriodBlocks: 6646
        isDepositsPaused: false
        isGuardian: null
        isMinDepositDistancePassed: null
    accountingOracleImpl:
      name: AccountingOracleImpl
      address: *accountingOracleImpl
      checks:
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        EXTRA_DATA_FORMAT_EMPTY: 0
        EXTRA_DATA_FORMAT_LIST: 1
        EXTRA_DATA_TYPE_EXITED_VALIDATORS: 2
        EXTRA_DATA_TYPE_STUCK_VALIDATORS: 1
        GENESIS_TIME: 1606824023
        LEGACY_ORACLE: *legacyOracle
        LIDO: *lido
        LOCATOR: *lidoLocator
        MANAGE_CONSENSUS_CONTRACT_ROLE: "0x04a0afbbd09d5ad397fc858789da4f8edd59f5ca5098d70faa490babee945c3b"
        MANAGE_CONSENSUS_VERSION_ROLE: "0xc31b1e4b732c5173dc51d519dfa432bad95550ecc4b0f9a61c2a558a2a8e4341"
        SECONDS_PER_SLOT: 12
        SUBMIT_DATA_ROLE: "0x65fa0c17458517c727737e4153dd477fa3e328cf706640b0f68b1a285c5990da"
        getConsensusContract: "0x0000000000000000000000000000000000000000"
        getConsensusReport: null
        getConsensusVersion: null
        getContractVersion: *maxUint256
        getLastProcessingRefSlot: null
        getProcessingState: null
        getRoleAdmin: null
        getRoleMember: null
        getRoleMemberCount: null
        hasRole: null
        supportsInterface: null
    oracleReportSanityChecker:
      name: OracleReportSanityChecker
      address: *oracleReportSanityChecker
      checks:
        ALL_LIMITS_MANAGER_ROLE: *ALL_LIMITS_MANAGER_ROLE
        ANNUAL_BALANCE_INCREASE_LIMIT_MANAGER_ROLE: *ANNUAL_BALANCE_INCREASE_LIMIT_MANAGER_ROLE
        APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE: *APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE: *EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE
        INITIAL_SLASHING_AND_PENALTIES_MANAGER_ROLE: *INITIAL_SLASHING_AND_PENALTIES_MANAGER_ROLE
        MAX_ITEMS_PER_EXTRA_DATA_TRANSACTION_ROLE: *MAX_ITEMS_PER_EXTRA_DATA_TRANSACTION_ROLE
        MAX_NODE_OPERATORS_PER_EXTRA_DATA_ITEM_ROLE: *MAX_NODE_OPERATORS_PER_EXTRA_DATA_ITEM_ROLE
        MAX_POSITIVE_TOKEN_REBASE_MANAGER_ROLE: *MAX_POSITIVE_TOKEN_REBASE_MANAGER_ROLE
        MAX_VALIDATOR_EXIT_REQUESTS_PER_REPORT_ROLE: *MAX_VALIDATOR_EXIT_REQUESTS_PER_REPORT_ROLE
        REQUEST_TIMESTAMP_MARGIN_MANAGER_ROLE: *REQUEST_TIMESTAMP_MARGIN_MANAGER_ROLE
        SECOND_OPINION_MANAGER_ROLE: *SECOND_OPINION_MANAGER_ROLE
        SHARE_RATE_DEVIATION_LIMIT_MANAGER_ROLE: *SHARE_RATE_DEVIATION_LIMIT_MANAGER_ROLE
        checkExitBusOracleReport:
          - args: [*oracleReportSanityCheckerMaxValidatorsExits]
            result: []
          - args: [*oracleReportSanityCheckerMaxValidatorsExitsRevert]
            mustRevert: true
        checkExitedValidatorsRatePerDay:
          - args: [*oracleReportSanityCheckerMaxValidatorsExitsPerDay]
            result: []
          - args: [*oracleReportSanityCheckerMaxValidatorsExitsPerDayRevert]
            mustRevert: true
        checkExtraDataItemsCountPerTransaction:
          - args: [*oracleReportSanityCheckerExtraDataItemPerTransaction]
            result: []
          - args: [*oracleReportSanityCheckerExtraDataItemPerTransactionRevert]
            mustRevert: true
        checkNodeOperatorsPerExtraDataItemCount:
          - args: [1, *oracleReportSanityCheckerNOPerExtraDataItem]
            result: []
          - args: [1, *oracleReportSanityCheckerNOPerExtraDataItemRevert]
            mustRevert: true
        checkSimulatedShareRate: null
        checkWithdrawalQueueOracleReport: null
        getLidoLocator: *lidoLocator
        getMaxPositiveTokenRebase: null
        getOracleReportLimits:
          - args: []
            result: *oracleReportSanityCheckerReportLimits
        getReportDataCount: null
        getRoleAdmin: null
        getRoleMember: null
        getRoleMemberCount:
          - args: [*ALL_LIMITS_MANAGER_ROLE]
            result: 0
          - args: [*ANNUAL_BALANCE_INCREASE_LIMIT_MANAGER_ROLE]
            result: 0
          - args: [*APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE]
            result: 0
          - args: [*DEFAULT_ADMIN_ROLE]
            result: 1
          - args: [*EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE]
            result: 0
          - args: [*INITIAL_SLASHING_AND_PENALTIES_MANAGER_ROLE]
            result: 0
          - args: [*MAX_ITEMS_PER_EXTRA_DATA_TRANSACTION_ROLE]
            result: 0
          - args: [*MAX_NODE_OPERATORS_PER_EXTRA_DATA_ITEM_ROLE]
            result: 0
          - args: [*MAX_POSITIVE_TOKEN_REBASE_MANAGER_ROLE]
            result: 0
          - args: [*MAX_VALIDATOR_EXIT_REQUESTS_PER_REPORT_ROLE]
            result: 0
          - args: [*REQUEST_TIMESTAMP_MARGIN_MANAGER_ROLE]
            result: 0
          - args: [*SECOND_OPINION_MANAGER_ROLE]
            result: 0
          - args: [*SHARE_RATE_DEVIATION_LIMIT_MANAGER_ROLE]
            result: 0
        hasRole:
          - args: [*DEFAULT_ADMIN_ROLE, *agent]
            result: true
        reportData: null
        secondOpinionOracle: *oracleReportSanityCheckerSecondOpinionOracle
        smoothenTokenRebase: null
        supportsInterface: null
    updateTargetValidatorLimits:
      name: UpdateTargetValidatorLimits
      address: *updateTargetValidatorLimits
      checks:
        trustedCaller: *sdvtCommittee
        nodeOperatorsRegistry: *sdvtModule
        createEVMScript: null
        decodeEVMScriptCallData: null
