parameters:
  - &WETH "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
  - &STETH "0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84"
  - &WSTETH "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
  - &LIDO_LOCATOR "0xC1d0b3DE6792Bf6b4b37EccdcC24e45978Cfd2Eb"
  - &WQ "0x889edC2eDab5f40e902b864aD4d7AdE8E412F9B1"
  - &CURATOR_ADMIN_MSIG "0x2E93913A796a6C6b2bB76F41690E78a2E206Be54"
  - &CURATOR_OPERATOR_EOA "0x2afc096981c2CFe3501bE4054160048718F6C0C8"
  - &DEPLOYER "0x188858AC61a74350116d1CB6958fBc509FD6afA1"
  - &GNOSIS_IMPL "0xd9db270c1b5e3bd161e8c8503c55ceabee709552"

misc:
  - &ZERO_ADDRESS "0x0000000000000000000000000000000000000000"
  - &SIMPLEDVT_MODULE_ID 2

  # Token params
  - &TOKEN_NAME "Decentralized Validator Token"
  - &TOKEN_SYMBOL "DVstETH"
  - &DECIMALS 18
  - &TVL_LIMIT "1000000000000000000" # 10^18
  - &D9 "1000000000" # 10^9
  - &Q96 "79228162514264337593543950336" # 2^96
  - &ONE_RATIO "1000000000000000000" # 10^18
  - &MAX_ALLOWED_REMAINDER "1000000000000000000" # 10^18 ???

  # ROLES
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &ADMIN_ROLE "0xf23ec0bb4210edd5cba85afd05127efcd2fc6a781bfed49188da1081670b22d8"
  - &ADMIN_DELEGATE_ROLE "0xc171260023d22a25a00a2789664c9334017843b831138c8ef03cc8897e5873d7"
  - &OPERATOR "0x46a52cf33029de9f84853745a87af28464c80bf0346df1b32e205fc73319f622"

deployed:
  l1:
    - &Vault "0xe2D2E90122cb203CF1565a37ef90a256843A825A"
    - &ERC20TvlModule "0x2c73350310C2b8c721d8192bd7620D1DCB1219ce"
    - &Initializer "0x969A0c7699ad0AC38fE05117c81D662762443E07"
    - &StakingModule "0xD570E16E3B62F05EcF3ff2706D331B7f56453adA"
    - &ManagedRatiosOracle "0xFeAFe509fae65962EF81555E3f078D58aF7ca3e9"
    - &ChainlinkOracle "0x39D5F9aEbBEcba99ED5d707b11d790387B5acB63"
    - &ConstantAggregatorV3 "0x278798AE6ea76ae75b381eA0D8DF140C1D5a7712"
    - &WStethRatiosAggregatorV3 "0x966a3b1c9d477D113630290F037b12349649d1bd"
    - &DefaultProxyImplementation "0xB8eF363E1909665c18BF0CB72Cba9a8152413A2E"
    - &VaultConfigurator "0xDee41701310f48744e6Bb4A5df6B5e714cE49133"
    - &ManagedValidator "0xA1b3a352c3fC7cfcBD36381CC2D0b157d6843473"
    - &SimpleDVTStakingStrategy "0x078b1C03d14652bfeeDFadf7985fdf2D8a2e8108"
    - &TransparentUpgradeableProxy "0x5E362eb2c0706Bd1d134689eC75176018385430B"
    - &ProxyAdmin "0x8E6C80c41450D3fA7B1Fd0196676b99Bfb34bF48"
    - &ProxyAdminMsig "0x81698f87C6482bF1ce9bFcfC0F103C4A0Adf0Af0"
    - &AdminMsig "0x9437B2a8cF3b69D782a61f9814baAbc172f72003"

l1:
  rpcUrl: https://ethereum-rpc.publicnode.com
  explorerHostname: api.etherscan.io
  explorerTokenEnv: ETHERSCAN_TOKEN
  contracts:
    Vault:
      name: Vault
      address: *Vault
      checks:
        ADMIN_DELEGATE_ROLE: *ADMIN_DELEGATE_ROLE
        ADMIN_ROLE: *ADMIN_ROLE
        D9: *D9
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        OPERATOR: *OPERATOR
        Q96: *Q96
        allowance: REPLACEME # need to specify args
        analyzeRequest: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        baseTvl: REPLACEME # ,
        calculateStack: REPLACEME # view call reverted
        configurator: *VaultConfigurator
        decimals: *DECIMALS
        getRoleAdmin: REPLACEME # need to specify args
        getRoleMember: REPLACEME # need to specify args
        getRoleMemberCount: REPLACEME # need to specify args
        hasRole: REPLACEME # need to specify args
        isAdmin: REPLACEME # need to specify args
        isOperator: REPLACEME # need to specify args
        isUnderlyingToken: REPLACEME # need to specify args
        name: ""
        pendingWithdrawers: REPLACEME #
        pendingWithdrawersCount: REPLACEME # 0
        requireAdmin: REPLACEME # need to specify args
        requireAtLeastOperator: REPLACEME # need to specify args
        supportsInterface: REPLACEME # need to specify args
        symbol: ""
        totalSupply: 0
        tvlModules: []
        underlyingTokens: []
        underlyingTvl: []
        withdrawalRequest: REPLACEME # need to specify args
    ERC20TvlModule:
      name: ERC20TvlModule
      address: *ERC20TvlModule
      checks:
        tvl: REPLACEME # need to specify args
    Initializer:
      name: Initializer
      address: *Initializer
      checks:
        ADMIN_DELEGATE_ROLE: *ADMIN_DELEGATE_ROLE
        ADMIN_ROLE: *ADMIN_ROLE
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        OPERATOR: *OPERATOR
        allowance: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        configurator: *ZERO_ADDRESS
        decimals: *DECIMALS
        getRoleAdmin: REPLACEME # need to specify args
        getRoleMember: REPLACEME # need to specify args
        getRoleMemberCount: REPLACEME # need to specify args
        hasRole: REPLACEME # need to specify args
        isAdmin: REPLACEME # need to specify args
        isOperator: REPLACEME # need to specify args
        name: "Initializer"
        requireAdmin: REPLACEME # need to specify args
        requireAtLeastOperator: REPLACEME # need to specify args
        supportsInterface: REPLACEME # need to specify args
        symbol: "init"
        totalSupply: 0
    StakingModule:
      name: StakingModule
      address: *StakingModule
      checks:
        lidoLocator: *LIDO_LOCATOR
        stakingModuleId: *SIMPLEDVT_MODULE_ID
        steth: *STETH
        weth: *WETH
        withdrawalQueue: *WQ
        wsteth: *WSTETH
    ManagedRatiosOracle:
      name: ManagedRatiosOracle
      address: *ManagedRatiosOracle
      checks:
        Q96: *Q96
        getTargetRatiosX96: REPLACEME # need to specify args
        vaultToData: REPLACEME # need to specify args
    ChainlinkOracle:
      name: ChainlinkOracle
      address: *ChainlinkOracle
      checks:
        Q96: *Q96
        aggregatorsData: REPLACEME # need to specify args
        baseTokens: REPLACEME # need to specify args
        getPrice: REPLACEME # need to specify args
        priceX96: REPLACEME # need to specify args
    ConstantAggregatorV3:
      name: ConstantAggregatorV3
      address: *ConstantAggregatorV3
      checks:
        answer: *ONE_RATIO # 1000000000000000000
        decimals: *DECIMALS
        latestRoundData: [0,*ONE_RATIO, 1722981035, 1722981035, 0]
    WStethRatiosAggregatorV3:
      name: WStethRatiosAggregatorV3
      address: *WStethRatiosAggregatorV3
      checks:
        decimals: *DECIMALS
        getAnswer: REPLACEME # 1175156638813790774
        latestRoundData: REPLACEME # 0,1175156638813790774,1722981035,1722981035,0
        wsteth: *WSTETH
    DefaultProxyImplementation:
      name: DefaultProxyImplementation
      address: *DefaultProxyImplementation
      checks:
        allowance: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        decimals: *DECIMALS
        name: ""
        symbol: ""
        totalSupply: 0
    VaultConfigurator:
      name: VaultConfigurator
      address: *VaultConfigurator
      checks:
        MAX_DELAY: REPLACEME # 31536000
        MAX_WITHDRAWAL_FEE: REPLACEME # 50000000
        areTransfersLocked: REPLACEME # false
        areTransfersLockedDelay: REPLACEME # 31536000
        baseDelay: REPLACEME # 2592000
        delegateModuleApprovalDelay: REPLACEME # 86400
        depositCallback: *ZERO_ADDRESS
        depositCallbackDelay: REPLACEME # 86400
        emergencyWithdrawalDelay: REPLACEME # 7776000
        isDelegateModuleApproved: REPLACEME # need to specify args
        isDepositLocked: REPLACEME # false
        isDepositLockedDelay: REPLACEME # 3600
        maximalTotalSupply: *TVL_LIMIT
        maximalTotalSupplyDelay: REPLACEME # 14400
        priceOracle: REPLACEME # 0x39D5F9aEbBEcba99ED5d707b11d790387B5acB63
        priceOracleDelay: REPLACEME # 2592000
        ratiosOracle: REPLACEME # 0xFeAFe509fae65962EF81555E3f078D58aF7ca3e9
        ratiosOracleDelay: REPLACEME # 2592000
        validator: *ManagedValidator
        validatorDelay: REPLACEME # 2592000
        vault: *TransparentUpgradeableProxy
        withdrawalCallback: *ZERO_ADDRESS
        withdrawalCallbackDelay: REPLACEME # 86400
        withdrawalFeeD9: REPLACEME # 0
        withdrawalFeeD9Delay: REPLACEME # 2592000
    ManagedValidator:
      name: ManagedValidator
      address: *ManagedValidator
      checks:
        ADMIN_ROLE_MASK: REPLACEME # 57896044618658097711785492504343953926634992332820282019728792003956564819968
        STORAGE_POSITION: REPLACEME # 0xc5d9a5dc0c3dbbd4debebdb870fda826372ee5f5ea588d9114d28c33a7f08b39
        allowAllSignaturesRoles: REPLACEME # need to specify args
        allowSignatureRoles: REPLACEME # need to specify args
        customValidator: REPLACEME # need to specify args
        hasPermission: REPLACEME # need to specify args
        publicRoles: REPLACEME # 1
        requirePermission: REPLACEME # need to specify args
        userRoles: REPLACEME # need to specify args
        validate: REPLACEME # need to specify args
    SimpleDVTStakingStrategy:
      name: SimpleDVTStakingStrategy
      address: *SimpleDVTStakingStrategy
      checks:
        ADMIN_DELEGATE_ROLE: REPLACEME # 0xc171260023d22a25a00a2789664c9334017843b831138c8ef03cc8897e5873d7
        ADMIN_ROLE: REPLACEME # 0xf23ec0bb4210edd5cba85afd05127efcd2fc6a781bfed49188da1081670b22d8
        DEFAULT_ADMIN_ROLE: REPLACEME # 0x0000000000000000000000000000000000000000000000000000000000000000
        OPERATOR: REPLACEME # 0x46a52cf33029de9f84853745a87af28464c80bf0346df1b32e205fc73319f622
        getRoleAdmin: REPLACEME # need to specify args
        getRoleMember: REPLACEME # need to specify args
        getRoleMemberCount: REPLACEME # need to specify args
        hasRole: REPLACEME # need to specify args
        isAdmin: REPLACEME # need to specify args
        isOperator: REPLACEME # need to specify args
        maxAllowedRemainder: *MAX_ALLOWED_REMAINDER
        requireAdmin: REPLACEME # need to specify args
        requireAtLeastOperator: REPLACEME # need to specify args
        stakingModule: *StakingModule
        supportsInterface: REPLACEME # need to specify args
        vault: *TransparentUpgradeableProxy
    TransparentUpgradeableProxy:
      name: Vault
      address: *TransparentUpgradeableProxy
      proxyName: TransparentUpgradeableProxy
      implementation: *Vault
      proxyChecks: {}
      checks:
        ADMIN_DELEGATE_ROLE: *ADMIN_DELEGATE_ROLE
        ADMIN_ROLE: *ADMIN_ROLE
        D9: *D9
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        OPERATOR: *OPERATOR
        Q96: *Q96
        allowance: REPLACEME # need to specify args
        analyzeRequest: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        baseTvl: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0,200010000000000
        calculateStack: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,79228162514264337593543950336,0,0,200010000000000,200010000000000,200010000000000,93105501159655653704807080512,1722981047,0,0x018398ce8790e11b884ffc900fe0a0f030a9792a9763e0fa6887ea3b5c12a49c
        configurator: *VaultConfigurator
        decimals: *DECIMALS
        getRoleAdmin: REPLACEME # need to specify args
        getRoleMember: REPLACEME # need to specify args
        getRoleMemberCount: REPLACEME # need to specify args
        hasRole: REPLACEME # need to specify args
        isAdmin: REPLACEME # need to specify args
        isOperator: REPLACEME # need to specify args
        isUnderlyingToken: REPLACEME # need to specify args
        name: *TOKEN_NAME
        pendingWithdrawers: []
        pendingWithdrawersCount: 0
        requireAdmin: REPLACEME # need to specify args
        requireAtLeastOperator: REPLACEME # need to specify args
        supportsInterface: REPLACEME # need to specify args
        symbol: *TOKEN_SYMBOL
        totalSupply: REPLACEME # 200010000000000
        tvlModules: [*ERC20TvlModule]
        underlyingTokens: [*WSTETH, *WETH]
        underlyingTvl: REPLACEME # 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0,0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,0,200010000000000
        withdrawalRequest: REPLACEME # need to specify args
      implementationChecks:
        ADMIN_DELEGATE_ROLE: *ADMIN_DELEGATE_ROLE
        ADMIN_ROLE: *ADMIN_ROLE
        D9: *D9
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        OPERATOR: *OPERATOR
        Q96: *Q96
        allowance: REPLACEME # need to specify args
        analyzeRequest: REPLACEME # need to specify args
        balanceOf: REPLACEME # need to specify args
        baseTvl: REPLACEME # ,
        calculateStack: REPLACEME # view call reverted
        configurator: *VaultConfigurator
        decimals: *DECIMALS
        getRoleAdmin: REPLACEME # need to specify args
        getRoleMember: REPLACEME # need to specify args
        getRoleMemberCount: REPLACEME # need to specify args
        hasRole: REPLACEME # need to specify args
        isAdmin: REPLACEME # need to specify args
        isOperator: REPLACEME # need to specify args
        isUnderlyingToken: REPLACEME # need to specify args
        name: ""
        pendingWithdrawers: REPLACEME #
        pendingWithdrawersCount: REPLACEME # 0
        requireAdmin: REPLACEME # need to specify args
        requireAtLeastOperator: REPLACEME # need to specify args
        supportsInterface: REPLACEME # need to specify args
        symbol: ""
        totalSupply: 0
        tvlModules: []
        underlyingTokens: []
        underlyingTvl: []
        withdrawalRequest: REPLACEME # need to specify args
    ProxyAdmin:
      name: ProxyAdmin
      address: *ProxyAdmin
      checks:
        UPGRADE_INTERFACE_VERSION: REPLACEME # 5.0.0
        owner: *ProxyAdminMsig
    ProxyAdminMsig:
      name: GnosisSafe
      address: *ProxyAdminMsig
      proxyName: GnosisSafeProxy
      implementation: *GNOSIS_IMPL
      proxyChecks: {}
      checks:
        VERSION: REPLACEME # 1.3.0
        approvedHashes: REPLACEME # need to specify args
        checkNSignatures: REPLACEME # need to specify args
        checkSignatures: REPLACEME # need to specify args
        domainSeparator: REPLACEME # 0x90468bd6f3155511c3cb7b455a07664de4779c3a328ac577fdd4cc584ee815d0
        encodeTransactionData: REPLACEME # need to specify args
        getChainId: REPLACEME # 1
        getModulesPaginated: REPLACEME # need to specify args
        getOwners: REPLACEME # 0xEA685f0AF4A0BF5E7D6729b2C63eDF574D3EE27f,0xa94e4ADceC38074967b17F6e8856AB12368686B5,0xFB864C1127ff77215d0A8e652bB632F526A4A89f,0x59F8D74Fe49d5ebEAc069E3baf07eB4b614BD5A7,0x185111c113d9B19Ea4C424D3cD8628A1ee09Be6A,0x06C3992a6067bEA8FB3Af7F004EdEbC13656761F,0x44A388BBD782AE1D7f4542aEb6C3569E2CfdF5a1,0x8888843c607F4Bbd6aD72128F478085256Bdd15D
        getStorageAt: REPLACEME # need to specify args
        getThreshold: REPLACEME # 5
        getTransactionHash: REPLACEME # need to specify args
        isModuleEnabled: REPLACEME # need to specify args
        isOwner: REPLACEME # need to specify args
        nonce: 2
        signedMessages: REPLACEME # need to specify args
      implementationChecks:
        VERSION: REPLACEME # 1.3.0
        approvedHashes: REPLACEME # need to specify args
        checkNSignatures: REPLACEME # need to specify args
        checkSignatures: REPLACEME # need to specify args
        domainSeparator: REPLACEME # 0xb0d1bc5d61a96b7e642e23eb0d9f7d3d53a1e9b75f5b28b8e68b1bdb8e9faecb
        encodeTransactionData: REPLACEME # need to specify args
        getChainId: REPLACEME # 1
        getModulesPaginated: REPLACEME # need to specify args
        getOwners: REPLACEME # view call reverted
        getStorageAt: REPLACEME # need to specify args
        getThreshold: REPLACEME # 1
        getTransactionHash: REPLACEME # need to specify args
        isModuleEnabled: REPLACEME # need to specify args
        isOwner: REPLACEME # need to specify args
        nonce: 0
        signedMessages: REPLACEME # need to specify args
    AdminMsig:
      name: GnosisSafe
      address: *AdminMsig
      proxyName: GnosisSafeProxy
      implementation: *GNOSIS_IMPL
      proxyChecks: {}
      checks:
        VERSION: REPLACEME # 1.3.0
        approvedHashes: REPLACEME # need to specify args
        checkNSignatures: REPLACEME # need to specify args
        checkSignatures: REPLACEME # need to specify args
        domainSeparator: REPLACEME # 0xb878d052f30ee1f255ef929297b38293fe1f43b47dfd27415997d75abae4d6c2
        encodeTransactionData: REPLACEME # need to specify args
        getChainId: REPLACEME # 1
        getModulesPaginated: REPLACEME # need to specify args
        getOwners: REPLACEME # 0xEA685f0AF4A0BF5E7D6729b2C63eDF574D3EE27f,0xa94e4ADceC38074967b17F6e8856AB12368686B5,0xFB864C1127ff77215d0A8e652bB632F526A4A89f,0x59F8D74Fe49d5ebEAc069E3baf07eB4b614BD5A7,0x185111c113d9B19Ea4C424D3cD8628A1ee09Be6A,0x06C3992a6067bEA8FB3Af7F004EdEbC13656761F,0x44A388BBD782AE1D7f4542aEb6C3569E2CfdF5a1,0x8888843c607F4Bbd6aD72128F478085256Bdd15D
        getStorageAt: REPLACEME # need to specify args
        getThreshold: REPLACEME # 5
        getTransactionHash: REPLACEME # need to specify args
        isModuleEnabled: REPLACEME # need to specify args
        isOwner: REPLACEME # need to specify args
        nonce: 27
        signedMessages: REPLACEME # need to specify args
      implementationChecks:
        VERSION: REPLACEME # 1.3.0
        approvedHashes: REPLACEME # need to specify args
        checkNSignatures: REPLACEME # need to specify args
        checkSignatures: REPLACEME # need to specify args
        domainSeparator: REPLACEME # 0xb0d1bc5d61a96b7e642e23eb0d9f7d3d53a1e9b75f5b28b8e68b1bdb8e9faecb
        encodeTransactionData: REPLACEME # need to specify args
        getChainId: REPLACEME # 1
        getModulesPaginated: REPLACEME # need to specify args
        getOwners: REPLACEME # view call reverted
        getStorageAt: REPLACEME # need to specify args
        getThreshold: REPLACEME # 1
        getTransactionHash: REPLACEME # need to specify args
        isModuleEnabled: REPLACEME # need to specify args
        isOwner: REPLACEME # need to specify args
        nonce: 0
        signedMessages: REPLACEME # need to specify args
