# Swell Mainnet Deployment & Configuration

parameters:
  - &wstETH "0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0"
  - &agent "0x3e40D73EB977Dc6a537aF587D48316feE66E9C8c"
  - &l1EmergencyBreaksMultisig "0x73b047fe6337183A454c5217241D780a932777bD"
  - &l2EmergencyBreaksMultisig "0xC2b778fCc3FF311Cf1abBF4E53880277bfD14C8f"
  - &l1CrossDomainMessenger "0xe6a99Ef12995DeFC5ff47EC0e13252f0E6903759"
  - &l2CrossDomainMessenger "0x4200000000000000000000000000000000000007"

deployed:
  l1:
    - &l1TokenBridge "0xecf3376512EDAcA4FBB63d2c67d12a0397d24121"
    - &l1TokenBridgeImpl "0x7e97935FbDF2a27EA35c4fdDdaCf5ACd685e65A2"
  l2:
    - &l2GovernanceExecutor "0xFF22ea467301010F1364fc154c13e0c86Fcfb077"
    - &l2TokenBridge "0x8311496799B8C2C7f13bC32c123ac4Eea068e6F0"
    - &l2TokenBridgeImpl "0x66ca84bC3C2dB33b6bd7B8994C033444C72b8ADE"
    - &l2WstETH "0x7c98E0779EB5924b3ba8cE3B17648539ed5b0Ecc"
    - &l2WstETHImpl "0xa1A3257813eD45d91e9c45E03C66FcDD54B4e7c1"

roles:
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &DEPOSITS_DISABLER_ROLE "0x63f736f21cb2943826cd50b191eb054ebbea670e4e962d0527611f830cd399d6"
  - &DEPOSITS_ENABLER_ROLE "0x4b43b36766bde12c5e9cbbc37d15f8d1f769f08f54720ab370faeb4ce893753a"
  - &WITHDRAWALS_DISABLER_ROLE "0x94a954c0bc99227eddbc0715a62a7e1056ed8784cd719c2303b685683908857c"
  - &WITHDRAWALS_ENABLER_ROLE "0x9ab8816a3dc0b3849ec1ac00483f6ec815b07eee2fd766a353311c823ad59d0d"


l1:
  rpcUrl: L1_MAINNET_RPC_URL
  contracts:
    tokenBridge:
      name: L1ERC20TokenBridge
      address: *l1TokenBridge
      proxyName: OssifiableProxy
      implementation: *l1TokenBridgeImpl
      proxyChecks:
        proxy__getImplementation: *l1TokenBridgeImpl
        proxy__getAdmin: *agent
        proxy__getIsOssified: false
      checks:
        isInitialized: true
        isDepositsEnabled: true
        isWithdrawalsEnabled: true
        l1Token: *wstETH
        l2Token: *l2WstETH
        l2TokenBridge: *l2TokenBridge
        messenger: *l1CrossDomainMessenger
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        DEPOSITS_DISABLER_ROLE: *DEPOSITS_DISABLER_ROLE
        DEPOSITS_ENABLER_ROLE: *DEPOSITS_ENABLER_ROLE
        WITHDRAWALS_DISABLER_ROLE: *WITHDRAWALS_DISABLER_ROLE
        WITHDRAWALS_ENABLER_ROLE: *WITHDRAWALS_ENABLER_ROLE
        getRoleAdmin: null
        hasRole: null
        supportsInterface: null
      implementationChecks:
        isInitialized: true
        isDepositsEnabled: false
        isWithdrawalsEnabled: false
        hasRole: null
      ozNonEnumerableAcl:
        *DEFAULT_ADMIN_ROLE : [*agent]
        *DEPOSITS_ENABLER_ROLE : [*agent]
        *DEPOSITS_DISABLER_ROLE : [*agent, *l1EmergencyBreaksMultisig]
        *WITHDRAWALS_ENABLER_ROLE : [*agent]
        *WITHDRAWALS_DISABLER_ROLE : [*agent, *l1EmergencyBreaksMultisig]

l2:
  rpcUrl: https://swell-mainnet.alt.technology
  contracts:
    governanceExecutor:
      name: OptimismBridgeExecutor
      address: *l2GovernanceExecutor
      checks:
        getEthereumGovernanceExecutor: *agent
        getGracePeriod: 86400
        getGuardian: "0x0000000000000000000000000000000000000000"
        getDelay: 0
        getMinimumDelay: 0
        getMaximumDelay: 1
        getActionsSetCount: 0
        OVM_L2_CROSS_DOMAIN_MESSENGER: *l2CrossDomainMessenger
        getActionsSetById: null
        getCurrentState: null
        isActionQueued: null
    wstETH:
      name: ERC20Bridged
      address: *l2WstETH
      proxyName: OssifiableProxy
      implementation: *l2WstETHImpl
      proxyChecks:
        proxy__getImplementation: *l2WstETHImpl
        proxy__getAdmin: *l2GovernanceExecutor
        proxy__getIsOssified: false
      checks:
        name: Wrapped liquid staked Ether 2.0
        symbol: wstETH
        decimals: 18
        bridge: *l2TokenBridge
        allowance: null
        balanceOf: null
        nonces: null
        totalSupply: null
      implementationChecks: {}
    tokenBridge:
      name: L2ERC20TokenBridge
      address: *l2TokenBridge
      proxyName: OssifiableProxy
      implementation: *l2TokenBridgeImpl
      proxyChecks:
        proxy__getImplementation: *l2TokenBridgeImpl
        proxy__getAdmin: *l2GovernanceExecutor
        proxy__getIsOssified: false
      checks:
        isDepositsEnabled: true
        isWithdrawalsEnabled: true
        isInitialized: true
        l1Token: *wstETH
        l2Token: *l2WstETH
        l1TokenBridge: *l1TokenBridge
        messenger: *l2CrossDomainMessenger
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        DEPOSITS_DISABLER_ROLE: *DEPOSITS_DISABLER_ROLE
        DEPOSITS_ENABLER_ROLE: *DEPOSITS_ENABLER_ROLE
        WITHDRAWALS_DISABLER_ROLE: *WITHDRAWALS_DISABLER_ROLE
        WITHDRAWALS_ENABLER_ROLE: *WITHDRAWALS_ENABLER_ROLE
        getRoleAdmin: null
        hasRole: null
        supportsInterface: null
      implementationChecks:
        isInitialized: true
        isDepositsEnabled: false
        isWithdrawalsEnabled: false
        hasRole: null
      ozAcl:
        *DEFAULT_ADMIN_ROLE : [*l2GovernanceExecutor]
        *DEPOSITS_DISABLER_ROLE : [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
        *DEPOSITS_ENABLER_ROLE : [*l2GovernanceExecutor]
        *WITHDRAWALS_DISABLER_ROLE : [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
        *WITHDRAWALS_ENABLER_ROLE : [*l2GovernanceExecutor]
