# Optimism Testnet Deployment & Configuration
# Checks current sepolia state

parameters:
  - &wstETH "0xB82381A3fBD3FaFA77B3a7bE693342618240067b"
  - &agent "0x32A0E5828B62AAb932362a4816ae03b860b65e83"
  - &l1EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l2EmergencyBreaksMultisig "0xa5F1d7D49F581136Cf6e58B32cBE9a2039C48bA1"
  - &l1CrossDomainMessenger "0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef"
  - &l2CrossDomainMessenger "0x4200000000000000000000000000000000000007"


deployed:
  l1:
    - &l1TokenBridge "0x4Abf633d9c0F4aEebB4C2E3213c7aa1b8505D332"
    - &l1TokenBridgeImpl "0x02825dbCaFbBfda57511dBD73d22c2787B653814"
  l2:
    - &l2GovernanceExecutor "0xf695357C66bA514150Da95b189acb37b46DDe602"
    - &l2TokenBridge "0xdBA2760246f315203F8B716b3a7590F0FFdc704a"
    - &l2TokenBridgeImpl "0x2B4a7968C173ea52745C3740B13da9609D83Bd82"
    - &l2WstETH "0x24B47cd3A74f1799b32B2de11073764Cb1bb318B"
    - &l2WstETHImpl "0xaB0c6F1015b644c252064155759Cdc90a6CBd50d"

roles:
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &DEPOSITS_DISABLER_ROLE "0x63f736f21cb2943826cd50b191eb054ebbea670e4e962d0527611f830cd399d6"
  - &DEPOSITS_ENABLER_ROLE "0x4b43b36766bde12c5e9cbbc37d15f8d1f769f08f54720ab370faeb4ce893753a"
  - &WITHDRAWALS_DISABLER_ROLE "0x94a954c0bc99227eddbc0715a62a7e1056ed8784cd719c2303b685683908857c"
  - &WITHDRAWALS_ENABLER_ROLE "0x9ab8816a3dc0b3849ec1ac00483f6ec815b07eee2fd766a353311c823ad59d0d"


l1:
  rpcUrl: L1_TESTNET_RPC_URL
  contracts:
    tokenBridge:
      name: L1ERC20TokenBridge
      address: *l1TokenBridge
      proxyName: OssifiableProxy
      implementation: *l1TokenBridgeImpl
      proxyChecks:
        proxy__getImplementation: *l1TokenBridgeImpl
        proxy__getAdmin: *agent
        proxy__getIsOssified: false
      checks:
        isInitialized: true
        isDepositsEnabled: true
        isWithdrawalsEnabled: true
        l1Token: *wstETH
        l2Token: *l2WstETH
        l2TokenBridge: *l2TokenBridge
        messenger: *l1CrossDomainMessenger
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        DEPOSITS_DISABLER_ROLE: *DEPOSITS_DISABLER_ROLE
        DEPOSITS_ENABLER_ROLE: *DEPOSITS_ENABLER_ROLE
        WITHDRAWALS_DISABLER_ROLE: *WITHDRAWALS_DISABLER_ROLE
        WITHDRAWALS_ENABLER_ROLE: *WITHDRAWALS_ENABLER_ROLE
        getRoleAdmin: null
        hasRole: null
        supportsInterface: null
      implementationChecks:
        isInitialized: true
        isDepositsEnabled: false
        isWithdrawalsEnabled: false
        hasRole:
          args: [*DEFAULT_ADMIN_ROLE, "0x0000000000000000000000000000000000000000"]
          result: true
      ozAcl:
        *DEFAULT_ADMIN_ROLE : [*agent]
        *DEPOSITS_DISABLER_ROLE : [*agent, *l1EmergencyBreaksMultisig]
        *WITHDRAWALS_DISABLER_ROLE : [*agent, *l1EmergencyBreaksMultisig]
        *WITHDRAWALS_ENABLER_ROLE : [*agent]

l2:
  rpcUrl: L2_TESTNET_RPC_URL
  contracts:
    governanceExecutor:
      name: OptimismBridgeExecutor
      address: *l2GovernanceExecutor
      checks:
        getEthereumGovernanceExecutor: *agent
        getGracePeriod: 86400
        getGuardian: "0xD06491e4C8B3107B83dC134894C4c96ED8ddbfa2"
        getDelay: 0
        getMinimumDelay: 0
        getMaximumDelay: 1
        getActionsSetCount: 18
        OVM_L2_CROSS_DOMAIN_MESSENGER: null
        getActionsSetById: null
        getCurrentState: null
        isActionQueued: null
    wstETH:
      name: ERC20Bridged
      address: *l2WstETH
      proxyName: OssifiableProxy
      implementation: *l2WstETHImpl
      proxyChecks:
        proxy__getImplementation: *l2WstETHImpl
        proxy__getAdmin: *l2GovernanceExecutor
        proxy__getIsOssified: false
      checks:
        name: Wrapped liquid staked Ether 2.0
        symbol: wstETH
        decimals: 18
        bridge: *l2TokenBridge
        DOMAIN_SEPARATOR: null
        PERMIT_TYPEHASH: null
        allowance: null
        balanceOf: null
        nonces: null
        totalSupply: null
      implementationChecks: {}
    tokenBridge:
      name: L2ERC20TokenBridge
      address: *l2TokenBridge
      proxyName: OssifiableProxy
      implementation: *l2TokenBridgeImpl
      proxyChecks:
        proxy__getImplementation: *l2TokenBridgeImpl
        proxy__getAdmin: *l2GovernanceExecutor
        proxy__getIsOssified: false
      checks:
        isDepositsEnabled: true
        isWithdrawalsEnabled: true
        isInitialized: true
        l1Token: *wstETH
        l2Token: *l2WstETH
        l1TokenBridge: *l1TokenBridge
        messenger: *l2CrossDomainMessenger
        DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
        DEPOSITS_DISABLER_ROLE: *DEPOSITS_DISABLER_ROLE
        DEPOSITS_ENABLER_ROLE: *DEPOSITS_ENABLER_ROLE
        WITHDRAWALS_DISABLER_ROLE: *WITHDRAWALS_DISABLER_ROLE
        WITHDRAWALS_ENABLER_ROLE: *WITHDRAWALS_ENABLER_ROLE
        getRoleAdmin: null
        hasRole: null
        supportsInterface: null
      implementationChecks:
        isInitialized: true
        isDepositsEnabled: false
        isWithdrawalsEnabled: false
        hasRole:
          args: [*DEFAULT_ADMIN_ROLE, "0x0000000000000000000000000000000000000000"]
          result: true
      ozAcl:
        *DEFAULT_ADMIN_ROLE : [*l2GovernanceExecutor]
        *DEPOSITS_DISABLER_ROLE : [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
        *DEPOSITS_ENABLER_ROLE : [*l2GovernanceExecutor]
        *WITHDRAWALS_DISABLER_ROLE : [*l2GovernanceExecutor, *l2EmergencyBreaksMultisig]
        *WITHDRAWALS_ENABLER_ROLE : [*l2GovernanceExecutor]
