---
parameters:
  - &lidoLocator "0x28FAB2059C713A7F9D8c86Db49f9bb0e96Af1ef8"
  - &lido "0x3F1c547b21f65e10480dE3ad8E19fAAC46C95034"
  - &stakingRouter "0xd6EbF043D30A7fe46D1Db32BA90a0A51207FE229"
  - &nodeOperatorRegistry "0x595F64Ddc3856a3b5Ff4f4CC1d1fb4B46cFd2bAC"
  - &simpleDVT "0x11a93807078f8BB880c1BD0ee4C387537de4b4b6"
  - &accountingOracle "0x4E97A3972ce8511D87F334dA17a2C332542a5246"
  - &agent "0xE92329EC7ddB11D25e25b3c21eeBf11f15eB325d"
  - &elRewardsVault "0xE73a3602b99f1f913e72F8bdcBC235e206794Ac8"
  - &legacyOracle "0x072f72BE3AcFE2c52715829F2CD9061A6C8fF019"
  - &burner "0x4E46BD7147ccf666E1d73A3A456fC7a68de82eCA"
  - &treasury "0xE92329EC7ddB11D25e25b3c21eeBf11f15eB325d"
  - &withdrawalQueue "0xc7cc160b58F8Bb0baC94b80847E2CF2800565C50"
  - &withdrawalVault "0xF0179dEC45a37423EAD4FaD5fCb136197872EAd9"
  - &oracleDaemonConfig "0xC01fC1F2787687Bc656EAc0356ba9Db6e6b7afb7"
  - &postTokenRebaseReceiver "0x072f72BE3AcFE2c52715829F2CD9061A6C8fF019"
  - &DEPOSIT_CONTRACT "0x4242424242424242424242424242424242424242"
  - &stakingModulesIds [1, 2, 3, 4]
  - &stakingModulesCount "4"
  - &lidoWithdrawalCredentials "0x010000000000000000000000f0179dec45a37423ead4fad5fcb136197872ead9"
  - &curatedType "0x637572617465642d6f6e636861696e2d76310000000000000000000000000000"
  - &dsmGuardians ["0x711B5fCfeD5A30CA78e0CAC321B060dE9D6f8979", "0xDAaE8C017f1E2a9bEC6111d288f9ebB165e0E163", "0x31fa51343297FFce0CC1E67a50B2D3428057D1b1", "0x43464Fe06c18848a2E2e913194D64c1970f4326a", "0x79A132BE0c25cED09e745629D47cf05e531bb2bb", "0x0bf1B3d1e6f78b12f26204348ABfCA9310259FfA", "0xf060ab3d5dCfdC6a0DFd5ca0645ac569b8f105CA"]
  - &accountingConsensus "0xa067FC95c22D51c3bC35fd4BE37414Ee8cc890d2"
  - &validatorsExitBusOracle "0xffDDF7025410412deaa05E3E1cE68FE53208afcb"
  - &validatorsExitBusOracleImpl "0x210f60EC8A4D020b3e22f15fee2d2364e9b22357"

deployed:
  l1:
    - &lidoLocatorImpl "0xa19a59aF0680F6D9676ABD77E1Ba7e4c205F55a0"
    - &stakingRouterImpl "0x9b5890E950E3Df487Bb64E0A6743cdE791139152"
    - &nodeOperatorRegistryImpl "0x41646708A7EDbe22BD635Cb838Ff9C0CfA99A3bE"
    - &simpleDVTImpl "0x41646708A7EDbe22BD635Cb838Ff9C0CfA99A3bE"
    - &depositSecurityModule "0x808DE3b26Be9438F12E9B45528955EA94C17f217"
    - &accountingOracleImpl "0x748CE008ac6b15634ceD5a6083796f75695052a2"
    - &oracleReportSanityChecker "0x80D1B1fF6E84134404abA18A628347960c38ccA7"

roles:
  - &DEFAULT_ADMIN_ROLE "0x0000000000000000000000000000000000000000000000000000000000000000"
  - &STAKING_MODULE_UNVETTING_ROLE "0x240525496a9dc32284b17ce03b43e539e4bd81414634ee54395030d793463b57"
  - &STAKING_MODULE_PAUSE_ROLE "0x00b1e70095ba5bacc3202c3db9faf1f7873186f0ed7b6c84e80c0018dcc6e38e"
  - &STAKING_MODULE_RESUME_ROLE "0x9a2f67efb89489040f2c48c3b2c38f719fba1276678d2ced3bd9049fb5edc6b2"
  - &STAKING_ROUTER_ROLE "0xbb75b874360e0bfd87f964eadd8276d8efb7c942134fc329b513032d0803e0c6"
  - &MANAGE_CONSENSUS_VERSION_ROLE "0xc31b1e4b732c5173dc51d519dfa432bad95550ecc4b0f9a61c2a558a2a8e4341"

l1:
  rpcUrl: L1_TESTNET_RPC_URL
  contracts:
    lidoLocator:
      name: LidoLocator
      address: *lidoLocator
      proxyName: OssifiableProxy
      implementation: *lidoLocatorImpl
      proxyChecks:
        proxy__getImplementation: *lidoLocatorImpl
        proxy__getAdmin: *agent
        proxy__getIsOssified: false
      checks:
        accountingOracle: *accountingOracle
        burner: *burner
        coreComponents: [*elRewardsVault, *oracleReportSanityChecker, *stakingRouter, *treasury, *withdrawalQueue, *withdrawalVault]
        depositSecurityModule: *depositSecurityModule
        elRewardsVault: *elRewardsVault
        legacyOracle: *legacyOracle
        lido: *lido
        oracleDaemonConfig: *oracleDaemonConfig
        oracleReportComponentsForLido: null
        oracleReportSanityChecker: *oracleReportSanityChecker
        postTokenRebaseReceiver: *postTokenRebaseReceiver
        stakingRouter: *stakingRouter
        treasury: *treasury
        validatorsExitBusOracle: *validatorsExitBusOracle
        withdrawalQueue: *withdrawalQueue
        withdrawalVault: *withdrawalVault
    stakingRouter:
      name: StakingRouter
      address: *stakingRouter
      proxyName: OssifiableProxy
      implementation: *stakingRouterImpl
      proxyChecks:
        proxy__getImplementation: *stakingRouterImpl
        proxy__getAdmin: *agent
        proxy__getIsOssified: false
      checks:
        DEFAULT_ADMIN_ROLE: null
        DEPOSIT_CONTRACT: *DEPOSIT_CONTRACT
        FEE_PRECISION_POINTS: null
        MANAGE_WITHDRAWAL_CREDENTIALS_ROLE: null
        MAX_STAKING_MODULES_COUNT: null
        MAX_STAKING_MODULE_NAME_LENGTH: null
        REPORT_EXITED_VALIDATORS_ROLE: null
        REPORT_REWARDS_MINTED_ROLE: null
        STAKING_MODULE_MANAGE_ROLE: null
        STAKING_MODULE_UNVETTING_ROLE: null
        TOTAL_BASIS_POINTS: null
        UNSAFE_SET_EXITED_VALIDATORS_ROLE: null
        getAllNodeOperatorDigests: null
        getAllStakingModuleDigests: null
        getContractVersion: 2
        getDepositsAllocation: null
        getLido: *lido
        getNodeOperatorDigests: null
        getNodeOperatorSummary: null
        getRoleAdmin:
          - args: [ *STAKING_MODULE_UNVETTING_ROLE ]
            result: *DEFAULT_ADMIN_ROLE
        getRoleMember:
          - args: [ *STAKING_MODULE_UNVETTING_ROLE, 0 ]
            result: *depositSecurityModule
          - args: [ *STAKING_MODULE_UNVETTING_ROLE, 1 ]
            result: []
            mustRevert: true
          - args: [ *STAKING_MODULE_PAUSE_ROLE, 0 ]
            result: []
            mustRevert: true
          - args: [ *STAKING_MODULE_RESUME_ROLE, 0 ]
            result: []
            mustRevert: true
        getRoleMemberCount:
          - args: [ *STAKING_MODULE_UNVETTING_ROLE ]
            result: 1
          - args: [ *DEFAULT_ADMIN_ROLE ]
            result: 1
        getStakingFeeAggregateDistribution: null
        getStakingFeeAggregateDistributionE4Precision: null
        getStakingModule: null
        getStakingModuleActiveValidatorsCount: null
        getStakingModuleDigests: null
        getStakingModuleIds: *stakingModulesIds
        getStakingModuleIsActive: null
        getStakingModuleIsDepositsPaused: null
        getStakingModuleIsStopped: null
        getStakingModuleLastDepositBlock: null
        getStakingModuleMaxDepositsCount: null
        getStakingModuleMaxDepositsPerBlock: null  # TODO recheck
        getStakingModuleMinDepositBlockDistance: null  # TODO recheck
        getStakingModuleNonce: null
        getStakingModuleStatus: null
        getStakingModuleSummary: null
        getStakingModules: null
        getStakingModulesCount: *stakingModulesCount
        getStakingRewardsDistribution: null
        getTotalFeeE4Precision: null
        getWithdrawalCredentials: *lidoWithdrawalCredentials
        hasRole:
          - args: [ *STAKING_MODULE_UNVETTING_ROLE, *depositSecurityModule ]
            result: true
          - args: [ *DEFAULT_ADMIN_ROLE, *agent ]
            result: true
        hasStakingModule: null
        supportsInterface: null
    nodeOperatorRegistry:
      name: NodeOperatorRegistry
      address: *nodeOperatorRegistry
      proxyName: AppProxyUpgradeable
      implementation: *nodeOperatorRegistryImpl
      proxyChecks:
        proxyType: null
        isDepositable: null
        implementation: *nodeOperatorRegistryImpl
        appId: null
        kernel: null
      checks:
        MANAGE_NODE_OPERATOR_ROLE: null
        MANAGE_SIGNING_KEYS: null
        MAX_NODE_OPERATORS_COUNT: null
        MAX_NODE_OPERATOR_NAME_LENGTH: null
        MAX_STUCK_PENALTY_DELAY: null
        SET_NODE_OPERATOR_LIMIT_ROLE: null
        STAKING_ROUTER_ROLE: *STAKING_ROUTER_ROLE
        appId: null
        allowRecoverability: null
        canPerform: null
        getActiveNodeOperatorsCount: null
        getContractVersion: 3
        getEVMScriptExecutor: null
        getEVMScriptRegistry: null
        getInitializationBlock: null
        getKeysOpIndex: null
        getLocator: *lidoLocator
        getNodeOperator: null
        getNodeOperatorIds: null
        getNodeOperatorIsActive: null
        getNodeOperatorSummary: null
        getNodeOperatorsCount: null
        getNonce: null
        getRecoveryVault: null
        getRewardDistributionState: null
        getRewardsDistribution: null
        getSigningKey: null
        getSigningKeys: null
        getStakingModuleSummary: null
        getStuckPenaltyDelay: null
        getTotalSigningKeyCount: null
        getType: *curatedType
        getUnusedSigningKeyCount: null
        hasInitialized: null
        isOperatorPenalized: null
        isOperatorPenaltyCleared: null
        isPetrified: null
        kernel: null
    simpleDVT:
      name: SimpleDVT
      address: *simpleDVT
      proxyName: AppProxyUpgradeable
      implementation: *simpleDVTImpl
      proxyChecks:
        proxyType: null
        isDepositable: null
        implementation: *simpleDVTImpl
        appId: null
        kernel: null
      checks:
        MANAGE_NODE_OPERATOR_ROLE: null
        MANAGE_SIGNING_KEYS: null
        MAX_NODE_OPERATORS_COUNT: null
        MAX_NODE_OPERATOR_NAME_LENGTH: null
        MAX_STUCK_PENALTY_DELAY: null
        SET_NODE_OPERATOR_LIMIT_ROLE: null
        STAKING_ROUTER_ROLE: *STAKING_ROUTER_ROLE
        appId: null
        allowRecoverability: null
        canPerform: null
        getActiveNodeOperatorsCount: null
        getContractVersion: 3
        getEVMScriptExecutor: null
        getEVMScriptRegistry: null
        getInitializationBlock: null
        getKeysOpIndex: null
        getLocator: *lidoLocator
        getNodeOperator: null
        getNodeOperatorIds: null
        getNodeOperatorIsActive: null
        getNodeOperatorSummary: null
        getNodeOperatorsCount: null
        getNonce: null
        getRecoveryVault: null
        getRewardDistributionState: null
        getRewardsDistribution: null
        getSigningKey: null
        getSigningKeys: null
        getStakingModuleSummary: null
        getStuckPenaltyDelay: null
        getTotalSigningKeyCount: null
        getType: *curatedType
        getUnusedSigningKeyCount: null
        hasInitialized: null
        isOperatorPenalized: null
        isOperatorPenaltyCleared: null
        isPetrified: null
        kernel: null
      depositSecurityModule:
        name: DepositSecurityModule
        address: *depositSecurityModule
        checks:
          ATTEST_MESSAGE_PREFIX: null
          DEPOSIT_CONTRACT: *DEPOSIT_CONTRACT
          LIDO: *lido
          PAUSE_MESSAGE_PREFIX: null
          STAKING_ROUTER: *stakingRouter
          UNVET_MESSAGE_PREFIX: null
          VERSION: 3
          canDeposit: null
          getGuardianIndex: null
          getGuardianQuorum: null
          getGuardians: *dsmGuardians
          getLastDepositBlock: null
          getMaxOperatorsPerUnvetting: null
          getOwner:
          getPauseIntentValidityPeriodBlocks: null
          isDepositsPaused: false
          isGuardian: null
          isMinDepositDistancePassed: null
        accountingOracle:
          name: AccountingOracle
          address: *accountingOracle
          proxyName: OssifiableProxy
          implementation: *accountingOracleImpl
          proxyChecks:
            proxy__getImplementation: *accountingOracleImpl
            proxy__getAdmin: *agent
            proxy__getIsOssified: false
          checks:
            DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
            EXTRA_DATA_FORMAT_EMPTY: null
            EXTRA_DATA_FORMAT_LIST: null
            EXTRA_DATA_TYPE_EXITED_VALIDATORS: null
            EXTRA_DATA_TYPE_STUCK_VALIDATORS: null
            GENESIS_TIME: null
            LEGACY_ORACLE: null
            LIDO: *lido
            LOCATOR: *lidoLocator
            MANAGE_CONSENSUS_CONTRACT_ROLE: null
            MANAGE_CONSENSUS_VERSION_ROLE: null
            SECONDS_PER_SLOT: null
            SUBMIT_DATA_ROLE: null
            getConsensusContract: *accountingConsensus
            getConsensusReport: null
            getConsensusVersion: 2
            getContractVersion: 2
            getLastProcessingRefSlot: null
            getProcessingState: null
            getRoleAdmin: null
            getRoleMember: null
            getRoleMemberCount: null
            hasRole: null
            supportsInterface: null
      oracleReportSanityChecker:
        name: OracleReportSanityChecker
        address: *oracleReportSanityChecker
        checks:
          ALL_LIMITS_MANAGER_ROLE: null
          ANNUAL_BALANCE_INCREASE_LIMIT_MANAGER_ROLE: null
          APPEARED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE: null
          DEFAULT_ADMIN_ROLE: *DEFAULT_ADMIN_ROLE
          EXITED_VALIDATORS_PER_DAY_LIMIT_MANAGER_ROLE: null
          INITIAL_SLASHING_AND_PENALTIES_MANAGER_ROLE: null
          MAX_ITEMS_PER_EXTRA_DATA_TRANSACTION_ROLE: null
          MAX_NODE_OPERATORS_PER_EXTRA_DATA_ITEM_ROLE: null
          MAX_POSITIVE_TOKEN_REBASE_MANAGER_ROLE: null
          MAX_VALIDATOR_EXIT_REQUESTS_PER_REPORT_ROLE: null
          REQUEST_TIMESTAMP_MARGIN_MANAGER_ROLE: null
          SECOND_OPINION_MANAGER_ROLE: null
          SHARE_RATE_DEVIATION_LIMIT_MANAGER_ROLE: null
          checkExitBusOracleReport: null  # TODO
          checkExitedValidatorsRatePerDay: null  # TODO
          checkExtraDataItemsCountPerTransaction: null  # TODO
          checkNodeOperatorsPerExtraDataItemCount: null  # TODO
          checkSimulatedShareRate: null  # TODO
          checkWithdrawalQueueOracleReport: null  # TODO
          getLidoLocator: *lidoLocator
          getMaxPositiveTokenRebase: null  # TODO
          getOracleReportLimits: null  # TODO
          getReportDataCount: null  # TODO
          getRoleAdmin: null  # TODO
          getRoleMember: null  # TODO
          getRoleMemberCount: null  # TODO
          hasRole: null  # TODO
          reportData: null
          secondOpinionOracle: null  # TODO
          smoothenTokenRebase: null  # TODO
          supportsInterface: null
      validatorsExitBusOracle:
        name: ValidatorsExitBusOracle
        address: *validatorsExitBusOracle
        proxyName: OssifiableProxy
        implementation: *validatorsExitBusOracleImpl
        proxyChecks:
          proxy__getAdmin: null
          proxy__getImplementation: null
          proxy__getIsOssified: null
        checks:
          DATA_FORMAT_LIST: null
          DEFAULT_ADMIN_ROLE: null
          GENESIS_TIME: null
          MANAGE_CONSENSUS_CONTRACT_ROLE: null
          MANAGE_CONSENSUS_VERSION_ROLE: *MANAGE_CONSENSUS_VERSION_ROLE
          PAUSE_INFINITELY: null
          PAUSE_ROLE: null
          RESUME_ROLE: null
          SECONDS_PER_SLOT: null
          SUBMIT_DATA_ROLE: null
          getConsensusContract: null
          getConsensusReport: null
          getConsensusVersion: 2
          getContractVersion: 1
          getLastProcessingRefSlot: null
          getLastRequestedValidatorIndices: null
          getProcessingState: null
          getResumeSinceTimestamp: null
          getRoleAdmin: null
          getRoleMember:
            - args: [*MANAGE_CONSENSUS_VERSION_ROLE, 0]
              result: []
              mustRevert: true
          getRoleMemberCount: null
          getTotalRequestsProcessed: null
          hasRole: null
          isPaused: null
          supportsInterface: null
